# Generated by Django 3.1.1 on 2020-10-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresume',
            name='education',
            field=models.CharField(choices=[('Среднее', 'Среднее'), ('Неполное высшее', 'Неполное высшее'), ('Отсутствует', 'Отсутствует'), ('Высшее', 'Высшее'), ('Средне-специальное', 'Средне-специальное')], max_length=32, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='level',
            field=models.CharField(choices=[('middle', 'middle'), ('lead', 'lead'), ('junior', 'junior'), ('senior', 'senior'), ('intern', 'intern')], max_length=32, verbose_name='Крутость'),
        ),
    ]
