# Generated by Django 3.1.1 on 2020-10-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Информация о компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='MEDIA_COMPANY_IMAGE_DIR', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='MEDIA_SPECIALITY_IMAGE_DIR', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='education',
            field=models.CharField(choices=[('Высшее', 'Высшее'), ('Отсутствует', 'Отсутствует'), ('Неполное высшее', 'Неполное высшее'), ('Средне-специальное', 'Средне-специальное'), ('Среднее', 'Среднее')], max_length=32, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='level',
            field=models.CharField(choices=[('lead', 'lead'), ('junior', 'junior'), ('intern', 'intern'), ('middle', 'middle'), ('senior', 'senior')], max_length=32, verbose_name='Крутость'),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='readiness',
            field=models.CharField(choices=[('Рассматриваю предложения', 'Рассматриваю предложения'), ('Не ищу работу', 'Не ищу работу'), ('Ищу работу', 'Ищу работу')], max_length=32, verbose_name='Готовность'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
