# Generated by Django 3.1.1 on 2020-10-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20201019_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresume',
            name='education',
            field=models.CharField(choices=[('Неполное высшее', 'Неполное высшее'), ('Отсутствует', 'Отсутствует'), ('Высшее', 'Высшее'), ('Средне-специальное', 'Средне-специальное'), ('Среднее', 'Среднее')], max_length=32, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='level',
            field=models.CharField(choices=[('senior', 'senior'), ('middle', 'middle'), ('lead', 'lead'), ('junior', 'junior'), ('intern', 'intern')], max_length=32, verbose_name='Крутость'),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='readiness',
            field=models.CharField(choices=[('Рассматриваю предложения', 'Рассматриваю предложения'), ('Ищу работу', 'Ищу работу'), ('Не ищу работу', 'Не ищу работу')], max_length=32, verbose_name='Готовность'),
        ),
    ]
